# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_pdf_translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(686, 527)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_translate = QtWidgets.QPushButton(Form)
        self.pushButton_translate.setObjectName("pushButton_translate")
        self.verticalLayout.addWidget(self.pushButton_translate)
        self.plainTextEdit_pdf_text = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_pdf_text.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_pdf_text.setOverwriteMode(True)
        self.plainTextEdit_pdf_text.setObjectName("plainTextEdit_pdf_text")
        self.verticalLayout.addWidget(self.plainTextEdit_pdf_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_translate.setText(_translate("Form", "翻译"))
