# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_pdf_translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdf_translate(object):
    def setupUi(self, pdf_translate):
        pdf_translate.setObjectName("pdf_translate")
        pdf_translate.resize(686, 527)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(pdf_translate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_translate = QtWidgets.QPushButton(pdf_translate)
        self.pushButton_translate.setObjectName("pushButton_translate")
        self.verticalLayout.addWidget(self.pushButton_translate)
        self.plainTextEdit_pdf_text = QtWidgets.QPlainTextEdit(pdf_translate)
        self.plainTextEdit_pdf_text.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_pdf_text.setOverwriteMode(True)
        self.plainTextEdit_pdf_text.setObjectName("plainTextEdit_pdf_text")
        self.verticalLayout.addWidget(self.plainTextEdit_pdf_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(pdf_translate)
        QtCore.QMetaObject.connectSlotsByName(pdf_translate)

    def retranslateUi(self, pdf_translate):
        _translate = QtCore.QCoreApplication.translate
        pdf_translate.setWindowTitle(_translate("pdf_translate", "PDF translator"))
        self.pushButton_translate.setText(_translate("pdf_translate", "翻译"))
